= Overview

Gramps, Family Tree Builder by MyHeritage, and Roots Magic all use SQLite,
an open source SQL database. There are several tools you can use to view 
and query SQLite3 databases:

Much of this analysis of the Roots Magic database came from the https://sqlitetoolsforrootsmagic.com[SQLite Tools for RootsMagic]
site.

== Common Table Expressions (CTE)

SQL Common Table Expressions (CTE) are like subqueries introduced before the main query that
can be reused throughout the query they precede. See https://www.sqlservertutorial.net/sql-server-basics/sql-server-cte/[Mastering Common Table Expressions].

== General SQL Questions

- Does creating and index `Create Index ...` on a table column imply that it is `UNIQUE`? If so, I need to note this. If so, I need to note this if I want to mimic it in my "extracted" MariaDB db. 
- Does the Data Definitions spreadsheet note this with `I`, too?

== How to Build SQL Views
 
Investigate this blog https://sqlitetoolsforrootsmagic.com/a-sample-query-created-with-views/[post] describing how to build complex SQL because the queries used fetch data I am interested in!!
