= Overview

Gramps, Family Tree Builder by MyHeritage, and Roots Magic use SQLite database.
It is an open source SQL implementation that manages--I believe--a sort of in-memory database.

There are several tools and utilites you can use to analyze and view
SQLite3 databases:

Musch of the analysis of Roots Magic came from https://sqlitetoolsforrootsmagic.com[SQLite Tools for RootsMagic].

== Common Table Expressions (CTE) Explained

SQL Common Table Expressions (CTE) are like subqueries that can be reused. See this
https://sqlitetoolsforrootsmagic.com/common-table-expressions-the-building-blocks-of-sql/[explanation]. 

== Workaround for RMNOCASE 

This is a custom RootsMagic collation sequence. It prevents `order by` from working in SQL statements. Instead use `lower(column-name)` for
use in `order by` clauses or for string comparisons.

== Questions

- Does creating and index `Create Index ...` on a table column imply that it is `UNIQUE`? If so, I need to note this. If so, I need to note this if I want to mimic it in my "extracted" MariaDB db. 
- Does the Data Definitions spreadsheet note this with `I`, too?

== Building Views
 
Investigate this blog https://sqlitetoolsforrootsmagic.com/a-sample-query-created-with-views/[post] describing how to build complex SQL because the queries used fetch data I am interested in!!
