= Overview

Gramps, Family Tree Builder by MyHeritage and Roots Magic all SQLite databases.
Listed below aree several SQLite database browsers.

Much of the analysis of the Roots Magic database derives from content on https://sqlitetoolsforrootsmagic.com[SQLite Tools for RootsMagic].

== SQLite Database Browsers and Tools

=== Ubuntu Packages

* https://sqlitebrowser.org/[sqlitebrower] package.
+
Included in Ubuntu as `sqlitebrowser` package
* `sqlite3-pcre` is an extension for sqlite3 that uses libpcre to provide +
the `REGEXP()` function.

Other third party packages include:

* https://jookdb.com/[JookDB] - SQLite support is only free during a 2 week trial.
* https://sqlitestudio.pl/[SQLiteStudio]
* https://www.beekeeperstudio.io/[Beekeeper Studio] - also works with MySQL, Postgress and SQL Server
* https://dbeaver.io[DB Beaver] - is an Eclipse-based product.

=== GEDCOM Tools

To convert GEDCOM to JSON or XML

The https://github.com/FamilySearch/gedcom5-java[gedcom5-java] FamilySearch github repo has a `Gedcom2Json` convertor.
It explains how to compile it using maven. Run it:

[source,bash]
----
$ java -cp target/gedcom.jar org.folg.gedcom.tools.Gedcom2Json
-i k.ged -o k.json 
----

== Common Table Expressions (CTE)

SQL Common Table Expressions (CTE) are variables that represent subqueries with a name. They are introduced before the main query
in which they are used. See:

* https://learnsql.com/blog/what-is-common-table-expression/[What are CTEs?]
* https://learnsql.com/blog/sql-common-table-expression-guide/[Guide to CTEs]
