= Name table Explained

A person `PersonTable.PersonID` may have more than one associated name. To implement this many-to-one relationship between the names an individual person, the 
`NameTable` has a foreign key `NameTable.OwnerID` that references `PersonsTable.PersonID`. The pair of attributes [`NameTable.Given`, `NameTable.Surname`] in each
row of `NameTable` is one of the `PersonTable.PersonID` possible names.

I'm not sure why `NameTable` has `BirthYear` and `DeathYear` attributes, but these attribute are always the same for a given `NameID`.

To reach this conclusion, these queries were done. First, if you count the number rows selected by the query

[source, sql]
----
SELECT
  OwnerID, 
  count(*) as total_names
from NameTable
group by OwnerID 
  having total_names > 1
order by OwnerID;
----

[source, cpp]
----
int a = 10;
class X {
  auto z = 11.0;
  
}
----

they are the same as when you attempt to further refine the grouping: `group by OwnerID, BirthYear, DeathYear`

[source, sql]
----
SELECT 
  OwnerID,
  BirthYear,
  DeathYear,
  count(*) as tuple_total
from NameTable
group by OwnerID, BirthYear, DeathYear
  having tuple_total > 1
----

Thus, joining these queries and selecting results and joining them  `where total_names != tuple_total` never returns anything:

[source, sql]
----
select r1.OwnerID, total_names, r2.BirthYear, r2.DeathYear, tuple_total
  from
   
  (SELECT 
    OwnerID,
    count(*) as total_names
  from NameTable
  group by OwnerID
    having total_names > 1) as r1

 join

   (SELECT 
      OwnerID,
      BirthYear,
      DeathYear,
      count(*) as tuple_total
    from NameTable
    group by OwnerID, BirthYear, DeathYear
      having tuple_total > 1) as r2

 on r1.OwnerID=r2.OwnerID
 where total_names !=t uple_total;
----
