site:
  title: Understand the Roots Magic SQLite Schema
  # the 404 page and sitemap files only get generated when the url property is set
  url: https://localhost
  start_page: genealogy-schemas::index.adoc
content:
  sources:
    - url: git@github.com:kurt-krueckeberg/roots-magic-analyzed
      branches: HEAD
      # start_path: docs
      # setting edit_url to false disables the Edit this Page link for any page that originates from this repository
      # the same thing can be achieved by adding empty credentials (i.e., @) in front of the domain in the URL
      edit_url: false
asciidoc:
  attributes:
    experimental: ""
    idprefix: ""
    idseparator: "-"
    page-pagination: ""
    extensions:
      - "@antora/lunr-extension"
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
# I copied these last two lines from https://gitlab.com/antora/docs.antora.org/-/blob/main/antora-playbook.yml
# because Gitlab Pages requires your static site's build process output files to be in a folder call "public".
output:
  dir: ./public
