= Schema and Designs
:toc:
:stylesheet: dark.css
:stylesdir: /home/kurt/asciidoctor-skins/css

== General

=== Tools

https://sqlitetoolsforrootsmagic.com[SQLite Tools] lists Sqlite tools.

=== Common Table Expressions (CTE) Explained

SQL Common Table Expressions (CTE) are like subqueries that can be reused. See this https://sqlitetoolsforrootsmagic.com/common-table-expressions-the-building-blocks-of-sql/[explanation]. 

=== Workaround for RMNOCASE 

This custom RM collation sequence prevents `order by` in SQL statements. Instead use `lower(column-name)` for comparisions or in `order by` clauses.

=== Questions

- Does creating and index `Create Index ...` on a table column imply that it is `UNIQUE`? If so, I need to note this. If so, I need to note this if I want to mimic it in my "extracted" MariaDB db. 
- Does the Data Definitions spreadsheet note this with `I`, too?

=== Views
 
Investigate this blog https://sqlitetoolsforrootsmagic.com/a-sample-query-created-with-views/[post] describing how to build complex SQL because the queries used fetch data I am interested in!!

== Gramps

include::gramps.adoc[]

== RootsMagic

include::roots-magic.adoc[]
